version: '3.8'
services:
  pos-ui-demo:
    container_name: edgify-pos-ui-demo
    image: 'edgify/edgify-pos-ui-demo:d92a2fc'
    environment:
      - REACT_APP_PREDICTOR_HOST=localhost
    #volumes:  
    #  - /etc/edgify/pos-ui/config.json:/usr/share/nginx/html/clients/config.json      
    ports:
      - '3000:80'
    networks:
      - edgify-network

  edgify-agent:
    container_name: edgify-agent
    image: 'edgify/edgify-agent:1.4.1-cpu'
    environment:
      - EDGIFY_API_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjMsImRldmljZUlkIjo0MCwicm9sZSI6IlJPTEVfREVWSUNFIiwidHlwZSI6InJlYWwiLCJpYXQiOjE1ODk3MTU5OTR9.NlmunBP1VeSR3too6fsBRbsOsX4GHzIBWnWq9-Gkl7Q
      - EDGIFY_API_BASE_URL=https://dashboard.prod.edgify.ai/api/v1/edge
      - EDGIFY_UPDATE_STATE_INTERVAL=60
      - EDGIFY_API_WEBSOCKET_ENDPOINT=dashboard.prod.edgify.ai
      - EDGIFY_API_WEBSOCKET_PROTOCOL=wss
      - EDGIFY_VIDEO_DEVICE=video0
      - EDGIFY_DEVICEMANAGER_WORKER_SHARED_FOLDER=/edgify_agent/shared/worker_shared
      - EDGIFY_DATAMANAGER_PATH=/edgify_agent/shared/samples
      - EDGIFY_DEVICEMANAGER_MODELS_FOLDER=/edgify_agent/shared/model
      - EDGIFY_DATABASE_PATH=/edgify_agent/shared/edgify.db
      - EDGIFY_VIDEOSTREAM_ENABLED=true
      - EDGIFY_DEVICEMANAGER_LOCAL_IP=127.0.0.1
      - EDGIFY_VIDEOSTREAM_CROP_ENABLE=false
#      - EDGIFY_VIDEOSTREAM_CROP_X1=166
#      - EDGIFY_VIDEOSTREAM_CROP_Y1=35
#      - EDGIFY_VIDEOSTREAM_CROP_X2=586
#      - EDGIFY_VIDEOSTREAM_CROP_Y2=425
#      - EDGIFY_VIDEOSTREAM_FRAME_WIDTH=640
#      - EDGIFY_VIDEOSTREAM_FRAME_HEIGHT=480      
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /edgify_agent/shared:/edgify_agent/shared
      - ~/.docker/config.json:/root/.docker/config.json
    devices:
      - /dev/video0:/dev/video0
    ports:
      - '8080:8080'
      - '9876:9876'
      - '50051:50051'
    networks:
      - edgify-network
networks:
  edgify-network:
    name: edgify-network
