version: '3'
services:
  edgify-pos-ui-demo: 
    image: edgify/edgify-pos-ui-demo
    container_name: edgify-pos-ui-demo
    environment:
      - REACT_APP_PREDICTOR_HOST=localhost
    ports:
      - '3000:80'
    networks: 
      - edgify-network      

  edgify-agent:
    image: edgify/edgify-agent:0.0.1
    container_name: edgify-agent
    devices:
      - '/dev/video0:/dev/video0'
    ports: 
      - '8080:8080'
    environment:
      - EDGIFY_DATABASE_PATH=/edgify/database/db_file
      - EDGIFY_DATAMANAGER_PATH=/edgify/datamanager
      - EDGIFY_API_TOKEN=
      - EDGIFY_API_BASE_URL=https://dashboard.prod.edgify.ai/api/v1/edge/    
    volumes: 
      - /etc/edgify/agent/database:/edgify/database
      - /etc/edgify/agent/datamanager:/edgify/datamanager
    networks: 
      - edgify-network      

  edgify-device-manager:
    container_name: edgify-device-manager
    image: edgify/edgify-device-manager:247f328
    environment:
      - EDGIFY_DEVICE_TOKEN=
      - EDGIFY_BASE_URL=https://dashboard.prod.edgify.ai/api/v1/edge
      - EDGIFY_UPDATE_STATE_INTERVAL=60
      - EDGIFY_SOCKET_URL=wss://dashboard.prod.edgify.ai/adonis-ws
      - EDGIFY_SHARED_FOLDER=/etc/edgify
      - EDGIFY_DATA_STREAM_FOLDER=/etc/edgify/stream-data
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock:rw
     - /etc/edgify/:/etc/edgify/
    networks: 
      - edgify-network
      
  netdata:
    container_name: netdata
    image: netdata/netdata
    environment:
      - PGID=999
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys.ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
    networks:
      - edgify-network
networks:
  edgify-network:     