#########################
# Edgify Version: 1.8.2 #
#########################
version: '3.8'
services:
  edgify-data-collector:
    restart: always 
    container_name: edgify-data-collector
    image: 'edgify/edgify-data-collector:1.7.2'
    #volumes:
    #  - /home/ubuntu/config.json:/usr/share/nginx/html/clients/config.json
    #  - /home/ubuntu/item_images/config.json:/usr/share/nginx/html/item_images/config.json
    #  - /home/ubuntu/item_images/images_pub:/usr/share/nginx/html/item_images/images_pub
    ports:
      - '3001:80'
    networks:
      - edgify-network
      
  edgify-agent:
    restart: always
    container_name: edgify-agent
    image: 'edgify/edgify-agent:1.8.3'
    environment:
      - EDGIFY_API_TOKEN=
      - EDGIFY_API_BASE_URL=https://dashboard.staging.edgify.ai/api/v1/edge
      - EDGIFY_UPDATE_STATE_INTERVAL=30
      - EDGIFY_API_WEBSOCKET_ENDPOINT=dashboard.staging.edgify.ai
      - EDGIFY_API_WEBSOCKET_PROTOCOL=wss
      - EDGIFY_DATAMANAGER_PATH=/edgify_agent/shared/samples
      - EDGIFY_DEVICEMANAGER_WORKER_SHARED_FOLDER=/edgify_agent/shared/worker_shared
      - EDGIFY_DEVICEMANAGER_MODELS_FOLDER=/edgify_agent/shared/model
      - EDGIFY_DEVICEMANAGER_LOCAL_IP=127.0.0.1
      - EDGIFY_DATABASE_PATH=/edgify_agent/shared/edgify.db
      - EDGIFY_VIDEO_DEVICE=video0
      - EDGIFY_VIDEOSTREAM_ENABLED=true
      - EDGIFY_VIDEOSTREAM_FRAMES_TO_GRAB=1
      - EDGIFY_VIDEOSTREAM_FRAME_WIDTH=640
      - EDGIFY_VIDEOSTREAM_FRAME_HEIGHT=480
      - EDGIFY_VIDEOSTREAM_FRAME_RATE=5
      - EDGIFY_PREDICTOR_FILTERING_MODEL_ID=
      - EDGIFY_PREDICTOR_FILTERING_MODEL_PATH=
      - EDGIFY_PREDICTOR_FILTERING_MODEL_CONFIG_PATH=      
      # - EDGIFY_VIDEOSTREAM_RECONNECT_ON_BLACK_SCREEN=true
      # - EDGIFY_VIDEOSTREAM_CROP_ENABLE=false
      # - EDGIFY_VIDEOSTREAM_CROP_X1=166
      # - EDGIFY_VIDEOSTREAM_CROP_Y1=35
      # - EDGIFY_VIDEOSTREAM_CROP_X2=586
      # - EDGIFY_VIDEOSTREAM_CROP_Y2=425
      # - EDGIFY_VIDEOSTREAM_USE_READ_INSTEAD_OF_GRAB=true
      # - EDGIFY_PREDICTOR_NUMBER_OF_CLASSES_TO_SHOW=4
      # - EDGIFY_PREDICTOR_CERTAINTY_ENABLED=false
      # - EDGIFY_PREDICTOR_TOP1_HIGH_CERTAINTY_THRESHOLD=0
      # - EDGIFY_PREDICTOR_MIN_CONFIDENCE_PER_PREDICTION=0
      # - EDGIFY_PREDICTOR_MIN_CONFIDENCE_SUM=0
      # - EDGIFY_PREDICTOR_LOOKUP_TABLE_PATH
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /edgify_agent/shared:/edgify_agent/shared
      - ~/.docker/config.json:/root/.docker/config.json
      #- ~/config.json:/edgify_agent/setup-ui/clients/config.json
    devices:
      - /dev/video0:/dev/video0
    ports:
      - '3000:3000'
      - '8080:8080'
      - '8090:8090'
      - '50051:50051'
    networks:
      - edgify-network

networks:
  edgify-network:
    name: edgify-network
